name: gendiff-test-and-linter-check

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.11
      - name: install-dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          make install
      - name: Analyze code with Python linter
        run: |
          make lint
      - name: Test and publish code coverage
        uses: paambaati/codeclimate-action@v3.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          coverageCommand: make test-coverage



        